### ISSUE TITLE
Non-realtime processing

### ISSUE THREAD

**Issue by Mijawel** [ricky0123/vad#1]
I am processing a wav file using the callbacks however I'm limited by the fact that it processes the file in real time, e.g. a 1 min audio file will take 1 min to process. 

Is it possible to process the file faster (similar to how the original python package does practically instantly)?

**Comment by ricky0123** [comment]
Yeah, I didn't create the library with that use case in mind. I can do a little refactoring to try to create a suitable API. Probably won't take very long.

**Comment by Mijawel** [comment]
Would be great if the library had that ability!

**Comment by ricky0123** [comment]
Okay I've added some initial support which you can see in action in the [file-bundler demo](https://vad-seven.vercel.app/). Did you want the timestamps within the audio file of when voice is detected? Or do you just want to run a callback on segments of audio with speech?

**Comment by Mijawel** [comment]
Looking for an array of timestamps when voice is detected within the file. Similar to the first section of the python colab:
https://colab.research.google.com/github/snakers4/silero-vad/blob/master/silero-vad.ipynb

![F314B9BF-EF53-42A9-9E20-F2C45F7AE0D1](https://user-images.githubusercontent.com/52743180/201210216-6d7707a7-acd9-46f3-9da8-ea0d207f8033.jpeg)

**Comment by tricedev** [comment]
@Mijawel please reach me via iamleatriceward@gmail.com 

Thanks.

**Comment by ricky0123** [comment]
I've added support for timestamps and changed the API a bit. You can see the documentation [here](https://github.com/ricky0123/vad#nonrealtimevad-node--browser). Hope that helps. For now it's the user's responsibility to decode the audio file into a Float32Array of samples.
