### ISSUE TITLE
(Very minor) Missing dependency

### ISSUE THREAD

**Issue by patconrey** [ricky0123/vad#12]
Hey! This is an amazing project. It's been a lot of fun to play around with! Last week I was trying to get it working with React. I was excited to see that you added the [react-bundler example](https://github.com/ricky0123/vad/tree/master/examples/react-bundler)!

I got it running, but `copy-webpack-plugin` wasn't listed in the [dependencies](https://github.com/ricky0123/vad/blob/master/examples/react-bundler/package.json), so I had to install it via `npm i copy-webpack-plugin`. It's a super minor thing, but I just wanted to bring it to your attention. Thank you so much for your work on this - it's such a cool project.

**Comment by ricky0123** [comment]
Fixed in master
