### ISSUE TITLE
Help in setting up next config as the files in node modules are missing next js

### ISSUE THREAD

**Issue by iammakk** [ricky0123/vad#137]
hey i need help . i want to setup vad with next js but the issue is. on rickyVad github examples i copy the next config but i get the error of the files in onnx-runtime web not found.
{
from: "./node_modules/onnxruntime-web/dist/ort-wasm.wasm",
to: "static/chunks/[name][ext]",
},
{
from: "./node_modules/onnxruntime-web/dist/ort-wasm-simd.wasm",
to: "static/chunks/[name][ext]",
},
can anyone help please??

**Comment by PrinceBaghel258025** [comment]
@iammakk it requires the file in static/chunks/page
here page simply indicates wherever you are using vad (these files should be exactly at the same place).
let's assume you are using at /dashboard/user/page => static/chunks/dashboard/user/[name][ext]

**Comment by ricky0123** [comment]
There are already a couple of open issues with people discussing issues related to Nextjs, so I'll close this. You can add a comment [here](https://github.com/ricky0123/vad/issues/106) if you run into any issues.
