### ISSUE TITLE
NextJS: unable to locate 'node_modules\onnxruntime-web\dist\*.wasm' glob

### ISSUE THREAD

**Issue by Facuiguacel** [ricky0123/vad#138]
Hi,
So when starting (npm run dev) or building a NextJS app with this package installed I just get this error:
`unable to locate 'C:\[..]\node_modules\onnxruntime-web\dist\*.wasm' glob`

The files are there. `ort-training-wasm-simd-threaded.wasm` `ort-wasm-simd-threaded.jsep.wasm` and `ort-wasm-simd-threaded.wasm`.

Anyone know what is going on? My workmate is not having this problem and is literally working on the same repo. Only difference is he is on MacOS and I'm on Windows.

**Comment by danielhangan** [comment]
I have the same problem but i am on macos

**Comment by krmanik** [comment]
May be
```diff
-          from: path.resolve(__dirname, 'node_modules/onnxruntime-web/dist/*.wasm'),
+          from: 'node_modules/onnxruntime-web/dist/*.wasm',
           to: '[name][ext]',
         },
         {
-          from: path.resolve(__dirname, 'node_modules/onnxruntime-web/dist/*.mjs'),
+          from: 'node_modules/onnxruntime-web/dist/*.mjs',
           to: '[name][ext]',
         },
```
