### ISSUE TITLE
[QUESTION] Opinions on how to use offline

### ISSUE THREAD

**Issue by Melona-BS** [ricky0123/vad#152]
I was wondering if I could make that vad package work offline as an example I use on the web.
If you've ever used a related source, or know anything, please let me know actively!

+) Current progress is attempting to import the ONNX model from the local path.

**Comment by Melona-BS** [comment]
I haven't tested it, but I managed to get the package from the local file path.
The file was downloaded from unpkg and referred to as a script.

script : ort.js dist / bundle.min.js / vad.worklet.bundle.min.js
model : silero_vad.onnx

```
const myvad = await vad.MicVAD.new({
				workletURL: // including file path "vad.worklet.bundle.min.js',
				modelURL: // including file path 'silero_vad.onnx',
				...
				ortConfig: (ort) => {
					ort.env.wasm.wasmPaths = // including dir path 'ort/dist/',
				},
			});
			myvad.start();
});
```

I hope this experiment will be helpful.

**Comment by xiaoBing5102** [comment]
Can you use it offline? The version you usedCan you use it offline? The version you used

**Comment by xiaoBing5102** [comment]
Can you use it offline? The version you used
