### ISSUE TITLE
Can we use submitUserSpeechOnPause?

### ISSUE THREAD

**Issue by stellacake** [ricky0123/vad#155]
Hi Ricky,
Is the parameter submitUserSpeechOnPause (officially) available?
I saw it only in your code --not in your documentation-- and it would be much cleaner to pass it with true than my workaround using a positive/negative count with onSpeechStart and onVADMisfire
Thank you!

**Comment by ricky0123** [comment]
Hey, yeah it works already. Documentation is out of date, sorry
