### ISSUE TITLE
Angular Issue

### ISSUE THREAD

**Issue by greglose** [ricky0123/vad#158]
Adding the   vad-web   to an angular 18 app. When launching I see the following error 👍 
./node_modules/onnxruntime-web/dist/ort.min.js:20:37-44 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

using import { MicVAD } from '@ricky0123/vad-web'; to add it to my component. 

Any work arounds? 

TIA

**Comment by vladP123ggg** [comment]
hello, try this whe initializing the app:
const myvad = await MicVAD.new({
      ortConfig: (ort) => {
        ort.env.wasm.wasmPaths = 'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.0/dist/';
      },
.... rest of the code
I am using this library in angular for some time, if you have any issues drop a line.

**Comment by Karuma303** [comment]
@vladP123ggg Thanks, that did the trick for me, but I do wonder, why it can't be loaded from my local path. Hmm... strange! ;)

**Comment by vladP123ggg** [comment]
I know... I had the same issue. I think it has to do with the path.... Did
you include it in the build?

**Comment by greglose** [comment]
Sorry I didn't thank you sooner - that did the trick.

**Comment by petridispa98** [comment]
Hello could be possible to share code for a basic setup for each framework, for example angular, vue, etc. So that anyone can quickly find the implementation for each framework she/he uses
