### ISSUE TITLE
Offline use problem

### ISSUE THREAD

**Issue by xiaoBing5102** [ricky0123/vad#168]
I introduced ort and bundle via script
The other dependencies are also placed in the public directory
But the run error is InferenceSeesion of undefined
Is offline use not allowed at present?
![Snipaste_2024-12-04_19-41-58](https://github.com/user-attachments/assets/53a40872-eb13-4932-bbb2-37443aebf3f1)

**Comment by xiaoBing5102** [comment]
Can the library be used offline

**Comment by ricky0123** [comment]
Hi @xiaoBing5102 yes it can be used offline. In addition to the comment I left in the other thread, make sure you are using onnxruntime-web version 1.14.0. I think that you are using a more recent version because IIRC ort-wasm-simd-threaded.mjs is not a part of 1.14.0
