### ISSUE TITLE
Feature Request:  Would it be possible pass in a MediaStream?

### ISSUE THREAD

**Issue by Mijawel** [ricky0123/vad#17]
Request:
Ability to pass a MediaStream to this VAD package

Background:
I am creating an app that shows a low quality realtime speech to text and then sends off larger chunks of audio for server processing.

So what I am doing so far, is getting a MediaStream from either getUserMedia or getDisplayMedia.
What I would like to do:
1. Give that MediaStream to VAD to detect chunks of speech and decode them immediately.
2. Give the same MediaStream to a MediaRecorder which gets 30 seconds chunks of the audio and sends them for transcription.

Right now however, the MicVad package uses getUserMedia directly so I don't have the option to use getDisplayMedia (or use the same stream in two applications)

Any chance this would be easy to add?

**Comment by ricky0123** [comment]
Yes, I think is a good idea. I'll try to look into it next week if I can. I don't think it will be too difficult.

**Comment by Instage** [comment]
I'm seeking to implement a very similar use case. Are there any updates on this @ricky0123?

**Comment by ricky0123** [comment]
Hi @Instage, thanks for the reminder. I've been busy but I haven't forgotten about it. I won't have time to get to it today, but hopefully in the next few days.

**Comment by maxbaluev** [comment]
Is there is any updates?

**Comment by ricky0123** [comment]
Okay it's done. Sorry for taking a while. Feel free to reopen if you have any problems.

**Comment by cipherhell** [comment]
How can the MediaStream be accessed?

**Comment by sandinmyjoints** [comment]
It's an option named `stream`. You can see it being used in a test case here: https://github.com/ricky0123/vad/commit/72b52f79970598a404d5ca8ba1731d76a7651390
