### ISSUE TITLE
How can I use this in nodejs

### ISSUE THREAD

**Issue by jlia0** [ricky0123/vad#172]
https://www.npmjs.com/package/@ricky0123/vad-node

Doesn't seem to have any documentation here.

**Comment by ricky0123** [comment]
Hi @jlia0 we no longer support node. Sorry about that

**Comment by psanders** [comment]
@jlia0 I created a port you can use as a reference:

https://github.com/fonoster/fonoster/tree/main/mods/autopilot/src/vad
