### ISSUE TITLE
Confusion around onnxruntime-web version

### ISSUE THREAD

**Issue by asktimfisher** [ricky0123/vad#174]
Hi! Been using this in a personal project for months - great job.

My question is around the web script version to use. Right now, I have this:

    <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.2/dist/ort.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@ricky0123/vad-web@0.0.19/dist/bundle.min.js"></script>

I see you're up to v21 but is it safe to keep the onnxruntime-web updated to their latest versions or should we wait for your example versions to update as reference for a best practice?

**Comment by ricky0123** [comment]
Hey @asktimfisher it's totally up to you. Honestly, if there is not a specific feature that is released that is relevant to you, you may as well keep using the old one. Glad you're enjoying it!

**Comment by asktimfisher** [comment]
Thanks!
