### ISSUE TITLE
Can't import 'utils' from "@ricky0123/vad-react"

### ISSUE THREAD

**Issue by rennn2002** [ricky0123/vad#27]
Hi, @ricky0123 
Thanks for creating such a great project!

Since the latest update to @ricky0123/vad-react(ver. 0.0.16) yesterday, it is no longer possible to import 'utils'.

I noticed that in @ricky0123/vad-react(0.0.16), the following code was excluded from [index.ts](https://github.com/ricky0123/vad/blob/master/packages/react/src/index.ts)

 `export { utils } from "@ricky0123/vad-web"`

Is there any reason why you removed the 'utils'?

Thank you in advance!

**Comment by ricky0123** [comment]
Yeah, my bad. Just added that back in.

**Comment by rennn2002** [comment]
> Yeah, my bad. Just added that back in.

Thank you a lot!!
