### ISSUE TITLE
VAD not working after onnxruntime-web updated to version 1.15.0

### ISSUE THREAD

**Issue by HayatoYagi** [ricky0123/vad#29]
Hi @ricky0123, Thanks for the nice project! I'm currently using vad-react in my app.

Since the release of onnxruntime-web package version 1.15.0 yesterday, I have noticed that the vad functionality is no longer working properly. I have attached the console log that includes relevant information. Could you please take a look at the log and provide any insights or suggestions to resolve this issue?

To address this problem temporarily, I believe it would be beneficial to revert the dependency version to 1.14.0 for now. This will involve fixing the dependency to onnxruntime-web at version 1.14.0 until the issue with version 1.15.0 is resolved.

Please let me know if there's any additional information I can provide!!

[localhost-1685066612858.log](https://github.com/ricky0123/vad/files/11570948/localhost-1685066612858.log)

**Comment by HayatoYagi** [comment]
After updating the wasm files, it seems that the issue has been resolved, and the functionality is now working as expected, just like before. I'm sorry for upsetting you.

**Comment by ricky0123** [comment]
Hi @HayatoYagi thanks for letting me know about this. So just to clarify, the problem was that you had updated onnxruntime-web but were still accidentally using the wasm files from the old version?

**Comment by HayatoYagi** [comment]
Yes, exactly!
