### ISSUE TITLE
Missing start of speech

### ISSUE THREAD

**Issue by lukestanley** [ricky0123/vad#3]
The start of voice audio is often missed, I expect it is classified as low probability at the start. I suspect that prepending X milliseconds of prior audio would help.

Found this via NPM, seems pretty cool, well done :)

I am unfamiliar with this code but will try having a look at how to prepend audio when voice activity is found.

**Comment by ricky0123** [comment]
Thanks for the kind words!

About prepending speech, it should currently be prepending a bit of audio according to the option `preSpeechPadFrames`. According to the defaults, it should be prepending 1 frame * 1536 samples per frame * 1000 milliseconds per 16000 samples, which comes out to roughly 100 milliseconds of audio. I'm still working on finding good defaults, and it's possible there is a bug with prepending the audio.

I've been meaning to write some documentation to explain all of this. I think I'm going to get started on that now.

**Comment by ricky0123** [comment]
This functionality is working. I upped the value on `preSpeechPadFrames` in the demo and am seeing better results. I [documented the algorithm in the README](https://github.com/ricky0123/vad#customizing-the-behavior-of-the-vad-algorithm) if you would like to read more.

**Comment by lukestanley** [comment]
That's great, pointing out preSpeechPadFrames really helped, thank you!
