### ISSUE TITLE
Pause VAD during speech not triggering `onSpeechEnd` or `onVADMisfire`

### ISSUE THREAD

**Issue by HayatoYagi** [ricky0123/vad#30]
Hi, @ricky0123 ! Thx for the useful project.

Currently, when `vad.pause()` is called during speech, neither `onSpeechEnd` nor `onVADMisfire` are triggered. As a result, the last speech section data is discarded. I believe that after `onSpeechStart` is called, either `onSpeechEnd` or `onVADMisfire` should always be triggered.

Expected Behavior:
If `vad.pause()` is called after `onSpeechStart` but before the end of the speech, there should be an implementation in place to trigger either `onSpeechEnd` or `onVADMisfire` at that point.

What do you think of this behavior? Please let me know if any further information or clarification is required!

**Comment by cipherhell** [comment]
I just found this to be as unintuitive as the author, coming here to find out if there's a way to manually trigger onspeechend - I haven't found one yet. How can this be done, or is there any other workaround? On another note I absolutely agree, this project is stunning and works impeccably well and is super reliable. thanks for the hard work

**Comment by ricky0123** [comment]
Hey, I appreciate both of your messages. I think the current behavior makes sense if it's the user clicking a button that triggers `vad.pause()`, because they are possibly taking a break from using the application and want to pause all functionality associated with the vad. Unfortunately, I'm not going to have time to work on this project for the foreseeable future, but I am happy to answer any questions you have and I hope my explanation gives you some sense of the motivation for the current behavior. I'm very happy you have found this project useful!

**Comment by ricky0123** [comment]
I don't have time to implement this myself, but one possible solution would be for the `onSpeechEnd` callback to take a second parameter that holds metadata like whether or not the speech segment was ended by calling `vad.pause`. I.e. people who want the current behavior would change their callback to 
```typescript
function onSpeechEnd(audio, { endedByManualPause }) {
    if (!endedByManualPause) {
        // do stuff
    }
}
```
Anyway, that is just one possible solution.

**Comment by cipherhell** [comment]
I'm unsure that addresses the question, maybe I can't read, but at least from my side I'm just looking to trigger 'onspeechend' manually. Any possibility to trigger that would suffice

**Comment by HayatoYagi** [comment]
@cipherhell 

> I'm just looking to trigger 'onspeechend' manually.

I think providing a direct way to trigger `onSpeechEnd` can be confusing and may introduce bugs. I guess you want to check if the voice is active and trigger `onSpeechEnd` iff it's true, right?
In my opinion, `vad.pause()` should naturally include that functionlity.

@ricky0123's suggestion seems reasonable for those who want to maintain the current behavior as well.

**Comment by antoine-lizee** [comment]
Hello there 👋 

I needed this behaviour too, so I pushed this [PR](https://github.com/ricky0123/vad/pull/45).

Note that I am not implementing the full solution of adding a parameter to `onSpeechEnd`, I'm just by default returning a `onSpeechEnd` and `onVADMisfire` when the `FrameProcessor` is paused. This is a breaking change and will probably not suit all use cases.

The patched modules are also available at @antoine-lizee/vad-..., just replace `ricky0123` in the package name by `antoine-lizee`.

My use case (for the record):
 - I use a pretty high value of redemptionFrames (16), to make sure I don't chunk the text in too many small pieces.
 - The user can press a button to stop the capture, with the expectation that he's done talking.
 - With the current behaviour, if the user presses right after being done, it falls in the redemptionFrames and discards the last chunk.

**Comment by ricky0123** [comment]
Hi everyone, you can now enable this behavior by passing in a [submitUserSpeechOnPause option](https://github.com/ricky0123/vad/blob/d34fcd628f2fdefceccb76e487d506373b152c22/test-site/src/submit-user-speech-on-pause/index.js#L12). Thanks to @antoine-lizee + @HayatoYagi for contributing code.

**Comment by antoine-lizee** [comment]
Amazing, thanks @ricky0123 !
Will test & switch to this when I get a chance.

**Comment by bayliner** [comment]
Great feature!!! Works well.
