### ISSUE TITLE
Custom asset path (.onnx / .wasm files)

### ISSUE THREAD

**Issue by pp-nz** [ricky0123/vad#42]
The library relies on certain assets, such as the 'silero_vad.onnx' file and other .wasm files. From what I can see the @ricky0123/vad-web will try to load these from the root of the webserver that is running the application (perhaps I've misunderstood this part).

In my implementation we bundle @ricky0123/vad-web into our own NPM package as part of a larger package. When someone installs the package that has @ricky0123/vad-web as a dependency the asset files unable to be loaded.

asset-path.ts sets a base path based on window.document.currentScript but this seems to be lost when loading `vad-web` via an intermediary package.

It would be ideal if we could specify the asset path for the .onnx / .wasm files to pull from our own path (some CDN we set up). Is there any way to achieve this with the current package?

**Comment by nikhedonia** [comment]
> asset-path.ts sets a base path based on window.document.currentScript but this seems to be lost when loading vad-web via an intermediary package.


to add to this: if bundlers are involved currentScript.src might be even misleading.
In next.js currentScript.src will be of the shape `/_next/chunks/chunk.<hash>.js` and the regex patterns will conclude that all assets are stored in `/_next/chunks` which is incorrect

**Comment by ricky0123** [comment]
Thanks for both of your comments. @nikhedonia's fix is available in the most recent version. You can see an example of it [here](https://github.com/ricky0123/vad/blob/0b30c5646e0be90ffec87dd1cc76e75321a30919/test-site/src/web-basic/index.js#L12-L13):

```javascript
    const myvad = await vad.MicVAD.new({
      workletURL: "http://localhost:8080/vad.worklet.bundle.min.js",
      modelURL: "http://localhost:8080/silero_vad.onnx",
```

I'll close this but free to leave more comments if they're related.
