### ISSUE TITLE
Consider configurable threshold with hysteresis instead of redemption frames

### ISSUE THREAD

**Issue by Azeirah** [ricky0123/vad#54]
I wrote a simple implementation for a thresholding function with configurable hysteresis. I don't have the theoretical background to know if it's "better" than simply having a redemption frame count as an alternative, but it does provide cleaner code.

Below code is my own code, feel free to use it if you prefer.

```ts
/**
 * Range is assumed to be between 0 and 1
 */
export default class ThresholdWithHysteresis {
  private activated = false;

  constructor(
    private threshold: number,
    private hysteresis = 0.1,
  ) {
    if (hysteresis > threshold) {
      throw new Error(
        "Value of the hysteresis must be lower than the threshold",
      );
    }
    if (threshold < 0 || threshold > 1 || hysteresis < 0 || hysteresis > 1) {
      throw new Error("Threshold and Hysteresis must be between 0 and 1");
    }
  }

  receive(value: number) {
    if (this.activated) {
      if (value > this.threshold - this.hysteresis) {
        return true;
      }
      this.activated = false;
      return false;
    }

    if (value > this.threshold) {
      this.activated = true;
      return true;
    }

    return false;
  }
}
```

Usage:

```ts
const threshold = new ThresholdWithHysteresis(0.5, 0.1);
onAudioFrameProcessed(function (confidence, audioFrame) {
  const isSpeaking = threshold.receive(confidence);

  if (isSpeaking) {...}
});
```

The idea of a threshold with hysteresis is that it activates once a signal crosses the threshold (ie, speech probability threshold = 0.2, isSpeech is 0.15, next frame is 0.21, it activates now).

However, once it has crossed the threshold, it will only "deactivate" once it has dropped below the threshold with the hysteresis value subtracted, ie

`new ThresholdWithHysteresis(0.2, 0.05)` activates at 0.2 but deactivates only when the value drops below 0.15.

Feel free to simply close this if you don't feel like it fits or is necessary, it's just a suggestion.

**Comment by ricky0123** [comment]
Hi @Azeirah , thanks for your message. Actually, I believe this is what we are currently doing, just with different terminology + the redemption frame idea. We have a "[negativeSpeechThreshold](https://github.com/ricky0123/vad/blob/99584e7daa02c65fd72e72cabdd7ea55f04321fc/packages/_common/src/frame-processor.ts#L21)", which I think plays the role of `this.threshold - this.hysteresis` in your code. I copied the algorithm from one of Silero's examples and might have changed the terminology. I don't know that I've tried setting redemption frames to 0, but if I did I think it would be equivalent to your algorithm.
