### ISSUE TITLE
How to make it deterministic

### ISSUE THREAD

**Issue by AmgadHasan** [ricky0123/vad#77]
Hello
This is a great tool. Thank you for contributing this to the community for free!

I have a question: how do I make the speech detection deterministic.

That is, when I send the same audio file 5 times to the tool, I should get the exact same result in those 5 times.

From my experience, sending the same audio  twice gives me different results

**Comment by ricky0123** [comment]
Hi @AmgadHasan this is a good question, I have never thought about it before. I'm tempted to say it's not possible. If you find a way to achieve this, perhaps using some setting of onnxruntime-web, you are welcome to share it here. But a quick search did not turn up anything useful

**Comment by ricky0123** [comment]
I'm tentatively marking this as "wontfix", but you are free to continue the discussion if you have any other comments
