### ISSUE TITLE
Controlling the duration of detecting

### ISSUE THREAD

**Issue by John-Luo925** [ricky0123/vad#78]
Hi, first of all, thank you so much for this awesome package, it's working great for me.
I am now wondering if I can control the duration of detection. For now, it detects "stop speaking" many times. Please let me know how can I do this ASAP.

**Comment by HayatoYagi** [comment]
You can configure some params. Please see the documentation here: https://wiki.vad.ricky0123.com/en/docs/user/algorithm

I believe increasing `redemptionFrames` would be effective for your situation!!

**Comment by John-Luo925** [comment]
Thanks for your comment. Do you know what the default `redeptionFrames` value is?

**Comment by HayatoYagi** [comment]
The default value is 8
https://github.com/ricky0123/vad/blob/9afa42d73981a7d9d7c6aee6c6e75e79f16bb9b6/packages/_common/src/frame-processor.ts#L56
