### ISSUE TITLE
Server Side Node not returning audio files async

### ISSUE THREAD

**Issue by jonahkaye** [ricky0123/vad#8]
Hi ricky, 

This repo is awesome thank you for building it. I am trying to use the NonRealTimeVad server side to process an audio file and run a transcription process on each VAD broken up piece. The issue I am having is that the for loop is not receiving the {audio,start,end} thruples as they are generated, and is instead getting them all in one batch at the end. Here is my code: 

```
async function main() {
    const nativeSampleRate = 16000; // 'en_example.wav' is 16kHz sample rate
    const audioSamples = loadWAV('clinical.wav');
    const audioFileData: Float32Array = new Float32Array(audioSamples);

    console.log(audioFileData.length)
    const options = {negativeSpeechThreshold: 0.5 - 0.15}
    const myvad = await vad.NonRealTimeVAD.new()
    let index = 1;
    let current_start = 0;
    for await (const {audio, start, end} of myvad.run(audioFileData, nativeSampleRate)) {
        console.log(start,end)
        // encode if end is greater than 30 seconds or its the last segment
        // if (end > 30000 * index)
        // {
            const audioSegment = audioFileData.slice(current_start *16, end *16);
            const wavBuffer = wav.encode(
                [audioSegment],
                {sampleRate: nativeSampleRate, float: true, bitDepth: 32 }
            );
            fs.writeFileSync(`audio_files/audio_segment_${index}.wav`, wavBuffer);
            // start some transcription process on the file. 
            index++;
            current_start = end;
        // }
    }
}
```

Any advice you might be able to give here would be super helpful. On a side note when I run: 

```
import {MicVAD, NonRealTimeVADOptions} from "@ricky0123/vad";
const fs = require('fs');
const wav = require('node-wav');
...
async function main() {
    const nativeSampleRate = 16000; // 'en_example.wav' is 16kHz sample rate
    const audioSamples = loadWAV('clinical.wav');
    const audioFileData: Float32Array = new Float32Array(audioSamples);

    console.log(audioFileData.length)
    const options: Partial<NonRealTimeVADOptions> = {negativeSpeechThreshold: 0.5 - 0.15}
    const myvad = await MicVAD.new(options)
...
}
```
I get an error like this: 
Property 'run' does not exist on type 'MicVAD' 

I think I followed the instructions in the readme I think, and any help here would also be appreciated. 
Thanks!

**Comment by ricky0123** [comment]
> The issue I am having is that the for loop is not receiving the {audio,start,end} thruples as they are generated, and is instead getting them all in one batch at the end.

Okay, that's not the intended behavior. I will look into it.

> I get an error like this:
> Property 'run' does not exist on type 'MicVAD'

Yeah, I know I haven't done a good job of making this clear in the README, but the `MicVAD` is only available in the browser (because it uses the webaudio api). Also, if you are running this using node, the import should be something like

```typescript
import {NonRealTimeVADOptions} from "@ricky0123/vad/dist/index.node";
```

I realize this is convoluted. My plan is to have two packages moving forward, one for the browser and another for node.

**Comment by ricky0123** [comment]
Hey, sorry for getting back to you so late on the first issue you mentioned. For node, when you call `NonRealTimeVAD.run`, it resamples all of the audio at once to a 16000 sample rate. Then it runs the VAD model on "frames" of resampled audio. The frame of audio is returned by the generator immediately after the VAD model runs. So the audio is partially processed all at once (for the resampling) and partially processed as the thruples are generated. I will probably change it in the future so the resampling is also done "on demand."
