### ISSUE TITLE
Initiate VAD on existing media stream

### ISSUE THREAD

**Issue by ScottDellinger** [ricky0123/vad#82]
I'd like to implement VAD on an existing stream (like below):

const stream = await this.mediaDevices.getUserMedia({ "audio": true, "video": constraints })

I'm already accessing and using tjhe video stream, but I'd like to detect voice activity within that same stream. Is that possible? I've taken a look through a lot of the code and documentation that I could find and I'm not sure where a good starting point would be. Would definitely appreciate a nudge in the right direction.

Thanks so much!

**Comment by HayatoYagi** [comment]
There is a `stream` option!

```
const myvad = await vad.MicVAD.new({
  stream: stream
  onSpeechStart: () => {
    console.log("Speech start")
  },
  onSpeechEnd: (arr) => {
    console.log("Speech end")
  },
})
```
